### ISSUE TITLE
Element #hello cannot be found

### ISSUE THREAD

**Issue by brandon14** [gianlucacandiotti/laravue#7]
I have installed this project on my Linux Mint install. I am using PHPStorm and I created a composer project and used the prwlr/laravue package. I ran npm install to get all the node packages, and then ran npm run build. That completed with no problem. I then ran npm run dev. It has the server up and running, and going to localhost:8080 shows a page that says @yeild('content'). The console has a warning log from Vue saying element #hello cannot be found. I am assuming that their is some problem with it loading the Hello.vue template and that is why nothing besides the @yeild is showing on the page. Any ideas as to what may be going on? Thanks man and this is a very nice laid out project might I add.

**Comment by brandon14** [comment]
So after some digging, changing the Ve element to attach to the body like it was before commit 9351c03f37db7f185c8e638f526a7f3333c3621d, it renders the page properly.

**Comment by gianlucacandiotti** [comment]
Hi, I just read your message, hmm let me clean install the project to check on the problem. Thanks !

**Comment by gianlucacandiotti** [comment]
Oh I should have read better and not waste time haha. You have to add **/dev** at the end of the url while in development. This is because it has to proxy the requests made to Webpack to Laravel and the only way to do that was giving it a context. In this case the context is **/dev**. At the end it should look like **localhost:8080/dev**.

I'm working on some things for this project because we're planning to use it for a big project in my company so everything has to work properly. I just have a problem with the redirections from the server while in development so it adds the **:8080/dev** portion to the urls.

Just carefully read the readme.md and you should be ok. I value the input I've been getting a lot so if you have any more comments or problems just tell me 😄 Thanks !
